"""Curated topical verse collections (KJV, public domain)."""


TOPIC_VERSES = [
    {
        "slug": "love", "title": "God's Love", "icon": "fa-heart",
        "description": "The love of God is the heartbeat of the whole Bible. Meditate on these verses whenever you need to be reminded of how deeply you are loved.",
        "verses": [
            {"reference": "John 3:16", "text": "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life."},
            {"reference": "1 John 4:8", "text": "He that loveth not knoweth not God; for God is love."},
            {"reference": "1 John 4:19", "text": "We love him, because he first loved us."},
            {"reference": "Romans 5:8", "text": "But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us."},
            {"reference": "1 Corinthians 13:4", "text": "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up,"},
            {"reference": "1 Corinthians 13:13", "text": "And now abideth faith, hope, charity, these three; but the greatest of these is charity."},
            {"reference": "John 13:34", "text": "A new commandment I give unto you, That ye love one another; as I have loved you, that ye also love one another."},
            {"reference": "John 15:13", "text": "Greater love hath no man than this, that a man lay down his life for his friends."},
        ],
    },
    {
        "slug": "faith", "title": "Faith", "icon": "fa-mountain",
        "description": "Faith is the foundation of the Christian life. These verses will strengthen your trust in the God who keeps every promise.",
        "verses": [
            {"reference": "Hebrews 11:1", "text": "Now faith is the substance of things hoped for, the evidence of things not seen."},
            {"reference": "Hebrews 11:6", "text": "But without faith it is impossible to please him: for he that cometh to God must believe that he is, and that he is a rewarder of them that diligently seek him."},
            {"reference": "2 Corinthians 5:7", "text": "(For we walk by faith, not by sight:)"},
            {"reference": "Romans 10:17", "text": "So then faith cometh by hearing, and hearing by the word of God."},
            {"reference": "Mark 11:24", "text": "Therefore I say unto you, What things soever ye desire, when ye pray, believe that ye receive them, and ye shall have them."},
            {"reference": "Matthew 17:20", "text": "And Jesus said unto them, Because of your unbelief: for verily I say unto you, If ye have faith as a grain of mustard seed, ye shall say unto this mountain, Remove hence to yonder place; and it shall remove; and nothing shall be impossible unto you."},
            {"reference": "1 John 5:4", "text": "For whatsoever is born of God overcometh the world: and this is the victory that overcometh the world, even our faith."},
            {"reference": "James 1:6", "text": "But let him ask in faith, nothing wavering. For he that wavereth is like a wave of the sea driven with the wind and tossed."},
        ],
    },
    {
        "slug": "hope", "title": "Hope", "icon": "fa-sun",
        "description": "Biblical hope is not wishful thinking — it is confident expectation in a faithful God. Let these promises lift your heart.",
        "verses": [
            {"reference": "Jeremiah 29:11", "text": "For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end."},
            {"reference": "Romans 15:13", "text": "Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost."},
            {"reference": "Isaiah 40:31", "text": "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint."},
            {"reference": "Psalm 42:11", "text": "Why art thou cast down, O my soul? and why art thou disquieted within me? hope thou in God: for I shall yet praise him, who is the health of my countenance, and my God."},
            {"reference": "Romans 12:12", "text": "Rejoicing in hope; patient in tribulation; continuing instant in prayer;"},
            {"reference": "Lamentations 3:22-23", "text": "It is of the LORD's mercies that we are not consumed, because his compassions fail not. They are new every morning: great is thy faithfulness."},
            {"reference": "Psalm 71:14", "text": "But I will hope continually, and will yet praise thee more and more."},
            {"reference": "1 Peter 1:3", "text": "Blessed be the God and Father of our Lord Jesus Christ, which according to his abundant mercy hath begotten us again unto a lively hope by the resurrection of Jesus Christ from the dead,"},
        ],
    },
    {
        "slug": "peace", "title": "Peace", "icon": "fa-dove",
        "description": "In a troubled world, God offers a peace that passes understanding. Rest in these promises of calm for your soul.",
        "verses": [
            {"reference": "John 14:27", "text": "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid."},
            {"reference": "Philippians 4:6-7", "text": "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God. And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus."},
            {"reference": "Isaiah 26:3", "text": "Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee."},
            {"reference": "Colossians 3:15", "text": "And let the peace of God rule in your hearts, to the which also ye are called in one body; and be ye thankful."},
            {"reference": "Psalm 29:11", "text": "The LORD will give strength unto his people; the LORD will bless his people with peace."},
            {"reference": "Romans 5:1", "text": "Therefore being justified by faith, we have peace with God through our Lord Jesus Christ:"},
            {"reference": "Matthew 5:9", "text": "Blessed are the peacemakers: for they shall be called the children of God."},
            {"reference": "Psalm 4:8", "text": "I will both lay me down in peace, and sleep: for thou, LORD, only makest me dwell in safety."},
        ],
    },
    {
        "slug": "strength", "title": "Strength", "icon": "fa-dumbbell",
        "description": "When you feel weak, God's strength is made perfect. Draw power from these verses for every battle you face.",
        "verses": [
            {"reference": "Philippians 4:13", "text": "I can do all things through Christ which strengtheneth me."},
            {"reference": "Isaiah 41:10", "text": "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness."},
            {"reference": "Psalm 46:1", "text": "God is our refuge and strength, a very present help in trouble."},
            {"reference": "Nehemiah 8:10", "text": "Then he said unto them, Go your way, eat the fat, and drink the sweet, and send portions unto them for whom nothing is prepared: for this day is holy unto our Lord: neither be ye sorry; for the joy of the LORD is your strength."},
            {"reference": "Isaiah 40:29", "text": "He giveth power to the faint; and to them that have no might he increaseth strength."},
            {"reference": "Ephesians 6:10", "text": "Finally, my brethren, be strong in the Lord, and in the power of his might."},
            {"reference": "Psalm 28:7", "text": "The LORD is my strength and my shield; my heart trusted in him, and I am helped: therefore my heart greatly rejoiceth; and with my song will I praise him."},
            {"reference": "2 Corinthians 12:9", "text": "And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness. Most gladly therefore will I rather glory in my infirmities, that the power of Christ may rest upon me."},
        ],
    },
    {
        "slug": "comfort", "title": "Comfort & Anxiety", "icon": "fa-hand-holding-heart",
        "description": "Cast your cares on the Lord — He cares for you. These verses are medicine for anxious hearts.",
        "verses": [
            {"reference": "Psalm 23:4", "text": "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me."},
            {"reference": "1 Peter 5:7", "text": "Casting all your care upon him; for he careth for you."},
            {"reference": "2 Timothy 1:7", "text": "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind."},
            {"reference": "Joshua 1:9", "text": "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest."},
            {"reference": "Psalm 34:4", "text": "I sought the LORD, and he heard me, and delivered me from all my fears."},
            {"reference": "Matthew 11:28", "text": "Come unto me, all ye that labour and are heavy laden, and I will give you rest."},
            {"reference": "John 14:1", "text": "Let not your heart be troubled: ye believe in God, believe also in me."},
            {"reference": "Psalm 56:3", "text": "What time I am afraid, I will trust in thee."},
            {"reference": "Matthew 6:34", "text": "Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself. Sufficient unto the day is the evil thereof."},
        ],
    },
    {
        "slug": "forgiveness", "title": "Forgiveness", "icon": "fa-hands-praying",
        "description": "Forgiven people forgive. Discover the freedom that comes from receiving and giving forgiveness.",
        "verses": [
            {"reference": "1 John 1:9", "text": "If we confess our sins, he is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness."},
            {"reference": "Ephesians 4:32", "text": "And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you."},
            {"reference": "Matthew 6:14", "text": "For if ye forgive men their trespasses, your heavenly Father will also forgive you:"},
            {"reference": "Colossians 3:13", "text": "Forbearing one another, and forgiving one another, if any man have a quarrel against any: even as Christ forgave you, so also do ye."},
            {"reference": "Psalm 103:12", "text": "As far as the east is from the west, so far hath he removed our transgressions from us."},
            {"reference": "Isaiah 1:18", "text": "Come now, and let us reason together, saith the LORD: though your sins be as scarlet, they shall be as white as snow; though they be red like crimson, they shall be as wool."},
            {"reference": "Luke 6:37", "text": "Judge not, and ye shall not be judged: condemn not, and ye shall not be condemned: forgive, and ye shall be forgiven:"},
            {"reference": "Acts 3:19", "text": "Repent ye therefore, and be converted, that your sins may be blotted out, when the times of refreshing shall come from the presence of the Lord;"},
        ],
    },
    {
        "slug": "healing", "title": "Healing", "icon": "fa-heart-pulse",
        "description": "Jehovah Rapha — the God who heals. Pray these scriptures over your body, mind and broken places.",
        "verses": [
            {"reference": "Jeremiah 17:14", "text": "Heal me, O LORD, and I shall be healed; save me, and I shall be saved: for thou art my praise."},
            {"reference": "Psalm 147:3", "text": "He healeth the broken in heart, and bindeth up their wounds."},
            {"reference": "Isaiah 53:5", "text": "But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed."},
            {"reference": "James 5:15", "text": "And the prayer of faith shall save the sick, and the Lord shall raise him up; and if he have committed sins, they shall be forgiven him."},
            {"reference": "Exodus 15:26", "text": "And said, If thou wilt diligently hearken to the voice of the LORD thy God, and wilt do that which is right in his sight, and wilt give ear to his commandments, and keep all his statutes, I will put none of these diseases upon thee, which I have brought upon the Egyptians: for I am the LORD that healeth thee."},
            {"reference": "Psalm 103:2-3", "text": "Bless the LORD, O my soul, and forget not all his benefits: Who forgiveth all thine iniquities; who healeth all thy diseases;"},
            {"reference": "3 John 1:2", "text": "Beloved, I wish above all things that thou mayest prosper and be in health, even as thy soul prospereth."},
            {"reference": "Psalm 30:2", "text": "O LORD my God, I cried unto thee, and thou hast healed me."},
        ],
    },
    {
        "slug": "wisdom", "title": "Wisdom", "icon": "fa-lightbulb",
        "description": "Wisdom is more precious than gold. Learn to walk skilfully through life with these verses as your guide.",
        "verses": [
            {"reference": "Proverbs 3:5-6", "text": "Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths."},
            {"reference": "James 1:5", "text": "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him."},
            {"reference": "Proverbs 9:10", "text": "The fear of the LORD is the beginning of wisdom: and the knowledge of the holy is understanding."},
            {"reference": "Proverbs 4:7", "text": "Wisdom is the principal thing; therefore get wisdom: and with all thy getting get understanding."},
            {"reference": "Proverbs 1:7", "text": "The fear of the LORD is the beginning of knowledge: but fools despise wisdom and instruction."},
            {"reference": "Psalm 111:10", "text": "The fear of the LORD is the beginning of wisdom: a good understanding have all they that do his commandments: his praise endureth for ever."},
            {"reference": "Proverbs 16:16", "text": "How much better is it to get wisdom than gold! and to get understanding rather to be chosen than silver!"},
            {"reference": "Colossians 3:16", "text": "Let the word of Christ dwell in you richly in all wisdom; teaching and admonishing one another in psalms and hymns and spiritual songs, singing with grace in your hearts to the Lord."},
        ],
    },
    {
        "slug": "prayer", "title": "Prayer", "icon": "fa-hands-praying",
        "description": "Prayer is simply talking with your Father. Let these verses fuel your prayer life with boldness and faith.",
        "verses": [
            {"reference": "Matthew 7:7", "text": "Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you:"},
            {"reference": "Jeremiah 33:3", "text": "Call unto me, and I will answer thee, and shew thee great and mighty things, which thou knowest not."},
            {"reference": "1 Thessalonians 5:16-18", "text": "Rejoice evermore. Pray without ceasing. In every thing give thanks: for this is the will of God in Christ Jesus concerning you."},
            {"reference": "James 5:16", "text": "Confess your faults one to another, and pray one for another, that ye may be healed. The effectual fervent prayer of a righteous man availeth much."},
            {"reference": "Psalm 145:18", "text": "The LORD is nigh unto all them that call upon him, to all that call upon him in truth."},
            {"reference": "Matthew 6:6", "text": "But thou, when thou prayest, enter into thy closet, and when thou hast shut thy door, pray to thy Father which is in secret; and thy Father which seeth in secret shall reward thee openly."},
            {"reference": "1 John 5:14", "text": "And this is the confidence that we have in him, that, if we ask any thing according to his will, he heareth us:"},
            {"reference": "Philippians 4:6", "text": "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God."},
        ],
    },
    {
        "slug": "gratitude", "title": "Gratitude", "icon": "fa-face-smile",
        "description": "A thankful heart changes everything. Count your blessings with these verses on thanksgiving and praise.",
        "verses": [
            {"reference": "1 Thessalonians 5:18", "text": "In every thing give thanks: for this is the will of God in Christ Jesus concerning you."},
            {"reference": "Psalm 100:4", "text": "Enter into his gates with thanksgiving, and into his courts with praise: be thankful unto him, and bless his name."},
            {"reference": "Psalm 107:1", "text": "O give thanks unto the LORD, for he is good: for his mercy endureth for ever."},
            {"reference": "Psalm 118:24", "text": "This is the day which the LORD hath made; we will rejoice and be glad in it."},
            {"reference": "Colossians 3:17", "text": "And whatsoever ye do in word or deed, do all in the name of the Lord Jesus, giving thanks to God and the Father by him."},
            {"reference": "Ephesians 5:20", "text": "Giving thanks always for all things unto God and the Father in the name of our Lord Jesus Christ;"},
            {"reference": "Psalm 9:1", "text": "I will praise thee, O LORD, with my whole heart; I will shew forth all thy marvellous works."},
            {"reference": "Psalm 136:1", "text": "O give thanks unto the LORD; for he is good: for his mercy endureth for ever."},
        ],
    },
    {
        "slug": "courage", "title": "Courage", "icon": "fa-shield-halved",
        "description": "Be strong and courageous — God goes before you. These verses will put steel in your spine for hard days.",
        "verses": [
            {"reference": "Deuteronomy 31:6", "text": "Be strong and of a good courage, fear not, nor be afraid of them: for the LORD thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee."},
            {"reference": "Joshua 1:9", "text": "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest."},
            {"reference": "1 Corinthians 16:13", "text": "Watch ye, stand fast in the faith, quit you like men, be strong."},
            {"reference": "Psalm 27:1", "text": "The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?"},
            {"reference": "Psalm 31:24", "text": "Be of good courage, and he shall strengthen your heart, all ye that hope in the LORD."},
            {"reference": "Matthew 14:27", "text": "But straightway Jesus spake unto them, saying, Be of good cheer; it is I; be not afraid."},
            {"reference": "Hebrews 13:6", "text": "So that we may boldly say, The Lord is my helper, and I will not fear what man shall do unto me."},
            {"reference": "Isaiah 41:10", "text": "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness."},
        ],
    },
    {
        "slug": "guidance", "title": "Guidance", "icon": "fa-compass",
        "description": "God promises to direct your steps. Seek His guidance for every decision with these scriptures.",
        "verses": [
            {"reference": "Psalm 32:8", "text": "I will instruct thee and teach thee in the way which thou shalt go: I will guide thee with mine eye."},
            {"reference": "Psalm 119:105", "text": "Thy word is a lamp unto my feet, and a light unto my path."},
            {"reference": "Isaiah 30:21", "text": "And thine ears shall hear a word behind thee, saying, This is the way, walk ye in it, when ye turn to the right hand, and when ye turn to the left."},
            {"reference": "Psalm 37:23", "text": "The steps of a good man are ordered by the LORD: and he delighteth in his way."},
            {"reference": "Proverbs 16:9", "text": "A man's heart deviseth his way: but the LORD directeth his steps."},
            {"reference": "Psalm 25:4", "text": "Shew me thy ways, O LORD; teach me thy paths."},
            {"reference": "Psalm 23:2-3", "text": "He maketh me to lie down in green pastures: he leadeth me beside the still waters. He restoreth my soul: he leadeth me in the paths of righteousness for his name's sake."},
            {"reference": "Proverbs 3:5-6", "text": "Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths."},
        ],
    },
    {
        "slug": "provision", "title": "Provision", "icon": "fa-hand-holding-dollar",
        "description": "Jehovah Jireh — the LORD will provide. Trust Him for your daily bread with these promises.",
        "verses": [
            {"reference": "Philippians 4:19", "text": "But my God shall supply all your need according to his riches in glory by Christ Jesus."},
            {"reference": "Matthew 6:33", "text": "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you."},
            {"reference": "Psalm 23:1", "text": "The LORD is my shepherd; I shall not want."},
            {"reference": "Psalm 37:25", "text": "I have been young, and now am old; yet have I not seen the righteous forsaken, nor his seed begging bread."},
            {"reference": "Malachi 3:10", "text": "Bring ye all the tithes into the storehouse, that there may be meat in mine house, and prove me now herewith, saith the LORD of hosts, if I will not open you the windows of heaven, and pour you out a blessing, that there shall not be room enough to receive it."},
            {"reference": "Psalm 34:10", "text": "The young lions do lack, and suffer hunger: but they that seek the LORD shall not want any good thing."},
            {"reference": "Genesis 22:14", "text": "And Abraham called the name of that place Jehovahjireh: as it is said to this day, In the mount of the LORD it shall be seen."},
            {"reference": "Luke 12:24", "text": "Consider the ravens: for they neither sow nor reap; which neither have storehouse nor barn; and God feedeth them: how much more are ye better than the fowls?"},
        ],
    },
    {
        "slug": "joy", "title": "Joy", "icon": "fa-champagne-glasses",
        "description": "The joy of the LORD is your strength. Rejoice today with these verses that overflow with gladness.",
        "verses": [
            {"reference": "Psalm 16:11", "text": "Thou wilt shew me the path of life: in thy presence is fulness of joy; at thy right hand there are pleasures for evermore."},
            {"reference": "John 15:11", "text": "These things have I spoken unto you, that my joy might remain in you, and that your joy might be full."},
            {"reference": "Psalm 30:5", "text": "For his anger endureth but a moment; in his favour is life: weeping may endure for a night, but joy cometh in the morning."},
            {"reference": "Philippians 4:4", "text": "Rejoice in the Lord alway: and again I say, Rejoice."},
            {"reference": "Galatians 5:22", "text": "But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith,"},
            {"reference": "Psalm 5:11", "text": "But let all those that put their trust in thee rejoice: let them ever shout for joy, because thou defendest them: let them also that love thy name be joyful in thee."},
            {"reference": "Psalm 118:24", "text": "This is the day which the LORD hath made; we will rejoice and be glad in it."},
            {"reference": "Nehemiah 8:10", "text": "Then he said unto them, Go your way, eat the fat, and drink the sweet, and send portions unto them for whom nothing is prepared: for this day is holy unto our Lord: neither be ye sorry; for the joy of the LORD is your strength."},
        ],
    },
    {
        "slug": "protection", "title": "Protection", "icon": "fa-shield-heart",
        "description": "God is your refuge and fortress. Pray these verses of protection over yourself and your loved ones.",
        "verses": [
            {"reference": "Psalm 91:1-2", "text": "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty. I will say of the LORD, He is my refuge and my fortress: my God; in him will I trust."},
            {"reference": "Psalm 121:7-8", "text": "The LORD shall preserve thee from all evil: he shall preserve thy soul. The LORD shall preserve thy going out and thy coming in from this time forth, and even for evermore."},
            {"reference": "2 Thessalonians 3:3", "text": "But the Lord is faithful, who shall stablish you, and keep you from evil."},
            {"reference": "Proverbs 18:10", "text": "The name of the LORD is a strong tower: the righteous runneth into it, and is safe."},
            {"reference": "Psalm 34:7", "text": "The angel of the LORD encampeth round about them that fear him, and delivereth them."},
            {"reference": "Nahum 1:7", "text": "The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him."},
            {"reference": "Psalm 121:1-2", "text": "I will lift up mine eyes unto the hills, from whence cometh my help. My help cometh from the LORD, which made heaven and earth."},
            {"reference": "John 10:28", "text": "And I give unto them eternal life; and they shall never perish, neither shall any man pluck them out of my hand."},
        ],
    },
    {
        "slug": "patience", "title": "Patience", "icon": "fa-hourglass-half",
        "description": "God's timing is perfect, even when it feels slow. Learn to wait well with these scriptures.",
        "verses": [
            {"reference": "Galatians 6:9", "text": "And let us not be weary in well doing: for in due season we shall reap, if we faint not."},
            {"reference": "James 1:3-4", "text": "Knowing this, that the trying of your faith worketh patience. But let patience have her perfect work, that ye may be perfect and entire, wanting nothing."},
            {"reference": "Psalm 27:14", "text": "Wait on the LORD: be of good courage, and he shall strengthen thine heart: wait, I say, on the LORD."},
            {"reference": "Romans 8:25", "text": "But if we hope for that we see not, then do we with patience wait for it."},
            {"reference": "Ecclesiastes 7:8", "text": "Better is the end of a thing than the beginning thereof: and the patient in spirit is better than the proud in spirit."},
            {"reference": "Hebrews 12:1", "text": "Wherefore seeing we also are compassed about with so great a cloud of witnesses, let us lay aside every weight, and the sin which doth so easily beset us, and let us run with patience the race that is set before us,"},
            {"reference": "Romans 12:12", "text": "Rejoicing in hope; patient in tribulation; continuing instant in prayer;"},
            {"reference": "Isaiah 40:31", "text": "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint."},
        ],
    },
    {
        "slug": "salvation", "title": "Salvation", "icon": "fa-cross",
        "description": "The greatest gift ever given. Meditate on the wonder of salvation through these core verses of the gospel.",
        "verses": [
            {"reference": "Romans 10:9", "text": "That if thou shalt confess with thy mouth the Lord Jesus, and shalt believe in thine heart that God hath raised him from the dead, thou shalt be saved."},
            {"reference": "Acts 4:12", "text": "Neither is there salvation in any other: for there is none other name under heaven given among men, whereby we must be saved."},
            {"reference": "Ephesians 2:8-9", "text": "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God: Not of works, lest any man should boast."},
            {"reference": "John 14:6", "text": "Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me."},
            {"reference": "Romans 6:23", "text": "For the wages of sin is death; but the gift of God is eternal life through Jesus Christ our Lord."},
            {"reference": "Acts 16:31", "text": "And they said, Believe on the Lord Jesus Christ, and thou shalt be saved, and thy house."},
            {"reference": "Titus 3:5", "text": "Not by works of righteousness which we have done, but according to his mercy he saved us, by the washing of regeneration, and renewing of the Holy Ghost;"},
            {"reference": "John 3:16", "text": "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life."},
        ],
    },
    {
        "slug": "humility", "title": "Humility", "icon": "fa-person-praying",
        "description": "God gives grace to the humble. Grow in Christ-like humility with these verses.",
        "verses": [
            {"reference": "James 4:10", "text": "Humble yourselves in the sight of the Lord, and he shall lift you up."},
            {"reference": "James 4:6", "text": "But he giveth more grace. Wherefore he saith, God resisteth the proud, but giveth grace unto the humble."},
            {"reference": "Philippians 2:3", "text": "Let nothing be done through strife or vainglory; but in lowliness of mind let each esteem other better than themselves."},
            {"reference": "Micah 6:8", "text": "He hath shewed thee, O man, what is good; and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?"},
            {"reference": "Proverbs 22:4", "text": "By humility and the fear of the LORD are riches, and honour, and life."},
            {"reference": "Matthew 23:12", "text": "And whosoever shall exalt himself shall be abased; and he that shall humble himself shall be exalted."},
            {"reference": "1 Peter 5:6", "text": "Humble yourselves therefore under the mighty hand of God, that he may exalt you in due time:"},
            {"reference": "Proverbs 11:2", "text": "When pride cometh, then cometh shame: but with the lowly is wisdom."},
        ],
    },
    {
        "slug": "new-beginnings", "title": "New Beginnings", "icon": "fa-seedling",
        "description": "God specialises in fresh starts. Step into your new season with these verses of renewal.",
        "verses": [
            {"reference": "2 Corinthians 5:17", "text": "Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new."},
            {"reference": "Isaiah 43:19", "text": "Behold, I will do a new thing; now it shall spring forth; shall ye not know it? I will even make a way in the wilderness, and rivers in the desert."},
            {"reference": "Lamentations 3:22-23", "text": "It is of the LORD's mercies that we are not consumed, because his compassions fail not. They are new every morning: great is thy faithfulness."},
            {"reference": "Isaiah 43:18", "text": "Remember ye not the former things, neither consider the things of old."},
            {"reference": "Philippians 3:13-14", "text": "Brethren, I count not myself to have apprehended: but this one thing I do, forgetting those things which are behind, and reaching forth unto those things which are before, I press toward the mark for the prize of the high calling of God in Christ Jesus."},
            {"reference": "Ezekiel 36:26", "text": "A new heart also will I give you, and a new spirit will I put within you: and I will take away the stony heart out of your flesh, and I will give you an heart of flesh."},
            {"reference": "Psalm 40:3", "text": "And he hath put a new song in my mouth, even praise unto our God: many shall see it, and fear, and shall trust in the LORD."},
            {"reference": "Revelation 21:5", "text": "And he that sat upon the throne said, Behold, I make all things new. And he said unto me, Write: for these words are true and faithful."},
        ],
    },
    {
        "slug": "money", "title": "Money & Stewardship", "icon": "fa-coins",
        "description": "Everything you own belongs to God — you are its steward. Learn how Scripture teaches us to handle money with wisdom and a generous heart.",
        "verses": [
            {"reference": "Proverbs 3:9", "text": "Honour the LORD with thy substance, and with the firstfruits of all thine increase:"},
            {"reference": "Matthew 6:24", "text": "No man can serve two masters: for either he will hate the one, and love the other; or else he will hold to the one, and despise the other. Ye cannot serve God and mammon."},
            {"reference": "1 Timothy 6:10", "text": "For the love of money is the root of all evil: which while some coveted after, they have erred from the faith, and pierced themselves through with many sorrows."},
            {"reference": "Malachi 3:10", "text": "Bring ye all the tithes into the storehouse, that there may be meat in mine house, and prove me now herewith, saith the LORD of hosts, if I will not open you the windows of heaven, and pour you out a blessing, that there shall not be room enough to receive it."},
            {"reference": "Luke 6:38", "text": "Give, and it shall be given unto you; good measure, pressed down, and shaken together, and running over, shall men give into your bosom. For with the same measure that ye mete withal it shall be measured to you again."},
            {"reference": "Matthew 6:19-21", "text": "Lay not up for yourselves treasures upon earth, where moth and rust doth corrupt, and where thieves break through and steal: But lay up for yourselves treasures in heaven, where neither moth nor rust doth corrupt, and where thieves do not break through nor steal: For where your treasure is, there will your heart be also."},
            {"reference": "Psalm 24:1", "text": "The earth is the LORD's, and the fulness thereof; the world, and they that dwell therein."},
            {"reference": "2 Corinthians 9:7", "text": "Every man according as he purposeth in his heart, so let him give; not grudgingly, or of necessity: for God loveth a cheerful giver."},
            {"reference": "Hebrews 13:5", "text": "Let your conversation be without covetousness; and be content with such things as ye have: for he hath said, I will never leave thee, nor forsake thee."},
        ],
    },
    {
        "slug": "family", "title": "Family & Children", "icon": "fa-people-roof",
        "description": "The family is God's first institution. These verses will help you build a home that honours Him — parents, children, husbands and wives.",
        "verses": [
            {"reference": "Psalm 127:3", "text": "Lo, children are an heritage of the LORD: and the fruit of the womb is his reward."},
            {"reference": "Proverbs 22:6", "text": "Train up a child in the way he should go: and when he is old, he will not depart from it."},
            {"reference": "Ephesians 6:1-2", "text": "Children, obey your parents in the Lord: for this is right. Honour thy father and mother; which is the first commandment with promise;"},
            {"reference": "Exodus 20:12", "text": "Honour thy father and thy mother: that thy days may be long upon the land which the LORD thy God giveth thee."},
            {"reference": "Deuteronomy 6:6-7", "text": "And these words, which I command thee this day, shall be in thine heart: And thou shalt teach them diligently unto thy children, and shalt talk of them when thou sittest in thine house, and when thou walkest by the way, and when thou liest down, and when thou risest up."},
            {"reference": "Joshua 24:15", "text": "And if it seem evil unto you to serve the LORD, choose you this day whom ye will serve; whether the gods which your fathers served that were on the other side of the flood, or the gods of the Amorites, in whose land ye dwell: but as for me and my house, we will serve the LORD."},
            {"reference": "Proverbs 17:6", "text": "Children's children are the crown of old men; and the glory of children are their fathers."},
            {"reference": "Ephesians 5:25", "text": "Husbands, love your wives, even as Christ also loved the church, and gave himself for it;"},
            {"reference": "Colossians 3:20", "text": "Children, obey your parents in all things: for this is well pleasing unto the Lord."},
        ],
    },
    {
        "slug": "work", "title": "Work & Diligence", "icon": "fa-briefcase",
        "description": "Work is worship. Whatever your hands find to do, these verses will inspire you to do it with all your heart, as unto the Lord.",
        "verses": [
            {"reference": "Colossians 3:23", "text": "And whatsoever ye do, do it heartily, as to the Lord, and not unto men;"},
            {"reference": "Proverbs 14:23", "text": "In all labour there is profit: but the talk of the lips tendeth only to penury."},
            {"reference": "Proverbs 10:4", "text": "He becometh poor that dealeth with a slack hand: but the hand of the diligent maketh rich."},
            {"reference": "Ecclesiastes 9:10", "text": "Whatsoever thy hand findeth to do, do it with thy might; for there is no work, nor device, nor knowledge, nor wisdom, in the grave, whither thou goest."},
            {"reference": "1 Corinthians 15:58", "text": "Therefore, my beloved brethren, be ye stedfast, unmoveable, always abounding in the work of the Lord, forasmuch as ye know that your labour is not in vain in the Lord."},
            {"reference": "Proverbs 22:29", "text": "Seest thou a man diligent in his business? he shall stand before kings; he shall not stand before mean men."},
            {"reference": "2 Thessalonians 3:10", "text": "For even when we were with you, this we commanded you, that if any would not work, neither should he eat."},
            {"reference": "Psalm 90:17", "text": "And let the beauty of the LORD our God be upon us: and establish thou the work of our hands upon us; yea, the work of our hands establish thou it."},
        ],
    },
    {
        "slug": "promises", "title": "Promises of God", "icon": "fa-handshake",
        "description": "God keeps every promise. When doubts come, anchor your soul in these verses about the faithfulness of the Promise-Keeper.",
        "verses": [
            {"reference": "2 Peter 1:4", "text": "Whereby are given unto us exceeding great and precious promises: that by these ye might be partakers of the divine nature, having escaped the corruption that is in the world through lust."},
            {"reference": "Numbers 23:19", "text": "God is not a man, that he should lie; neither the son of man, that he should repent: hath he said, and shall he not do it? or hath he spoken, and shall he not make it good?"},
            {"reference": "Joshua 21:45", "text": "There failed not ought of any good thing which the LORD had spoken unto the house of Israel; all came to pass."},
            {"reference": "Hebrews 10:23", "text": "Let us hold fast the profession of our faith without wavering; (for he is faithful that promised;)"},
            {"reference": "2 Corinthians 1:20", "text": "For all the promises of God in him are yea, and in him Amen, unto the glory of God by us."},
            {"reference": "Isaiah 55:11", "text": "So shall my word be that goeth forth out of my mouth: it shall not return unto me void, but it shall accomplish that which I please, and it shall prosper in the thing whereto I sent it."},
            {"reference": "1 Kings 8:56", "text": "Blessed be the LORD, that hath given rest unto his people Israel, according to all that he promised: there hath not failed one word of all his good promise, which he promised by the hand of Moses his servant."},
            {"reference": "Psalm 145:13", "text": "Thy kingdom is an everlasting kingdom, and thy dominion endureth throughout all generations."},
            {"reference": "Romans 4:21", "text": "And being fully persuaded that, what he had promised, he was able also to perform."},
        ],
    },
    {
        "slug": "truth", "title": "Truth", "icon": "fa-scale-balanced",
        "description": "Jesus is the way, the truth and the life. In a world of shifting opinions, let these verses anchor you in what is eternally true.",
        "verses": [
            {"reference": "John 8:32", "text": "And ye shall know the truth, and the truth shall make you free."},
            {"reference": "John 14:6", "text": "Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me."},
            {"reference": "John 17:17", "text": "Sanctify them through thy truth: thy word is truth."},
            {"reference": "Psalm 25:5", "text": "Lead me in thy truth, and teach me: for thou art the God of my salvation; on thee do I wait all the day."},
            {"reference": "Proverbs 12:22", "text": "Lying lips are abomination to the LORD: but they that deal truly are his delight."},
            {"reference": "Ephesians 4:25", "text": "Wherefore putting away lying, speak every man truth with his neighbour: for we are members one of another."},
            {"reference": "John 16:13", "text": "Howbeit when he, the Spirit of truth, is come, he will guide you into all truth: for he shall not speak of himself; but whatsoever he shall hear, that shall he speak: and he will shew you things to come."},
            {"reference": "3 John 1:4", "text": "I have no greater joy than to hear that my children walk in truth."},
            {"reference": "1 John 3:18", "text": "My little children, let us not love in word, neither in tongue; but in deed and in truth."},
        ],
    },
    {
        "slug": "contentment", "title": "Contentment", "icon": "fa-mug-hot",
        "description": "Godliness with contentment is great gain. Learn the secret of being at rest — no matter your circumstances.",
        "verses": [
            {"reference": "Philippians 4:11", "text": "Not that I speak in respect of want: for I have learned, in whatsoever state I am, therewith to be content."},
            {"reference": "1 Timothy 6:6", "text": "But godliness with contentment is great gain."},
            {"reference": "Psalm 37:16", "text": "A little that a righteous man hath is better than the riches of many wicked."},
            {"reference": "Proverbs 30:8-9", "text": "Remove far from me vanity and lies: give me neither poverty nor riches; feed me with food convenient for me: Lest I be full, and deny thee, and say, Who is the LORD? or lest I be poor, and steal, and take the name of my God in vain."},
            {"reference": "Matthew 6:25", "text": "Therefore I say unto you, Take no thought for your life, what ye shall eat, or what ye shall drink; nor yet for your body, what ye shall put on. Is not the life more than meat, and the body than raiment?"},
            {"reference": "Luke 12:15", "text": "And he said unto them, Take heed, and beware of covetousness: for a man's life consisteth not in the abundance of the things which he possesseth."},
            {"reference": "Psalm 23:1", "text": "The LORD is my shepherd; I shall not want."},
            {"reference": "2 Corinthians 9:8", "text": "And God is able to make all grace abound toward you; that ye, always having all sufficiency in all things, may abound to every good work:"},
        ],
    },
    {
        "slug": "obedience", "title": "Obedience", "icon": "fa-list-check",
        "description": "To obey is better than sacrifice. Discover the joy and blessing that follow a heart quick to say 'Yes, Lord.'",
        "verses": [
            {"reference": "John 14:15", "text": "If ye love me, keep my commandments."},
            {"reference": "1 Samuel 15:22", "text": "And Samuel said, Hath the LORD as great delight in burnt offerings and sacrifices, as in obeying the voice of the LORD? Behold, to obey is better than sacrifice, and to hearken than the fat of rams."},
            {"reference": "James 1:22", "text": "But be ye doers of the word, and not hearers only, deceiving your own selves."},
            {"reference": "Luke 11:28", "text": "But he said, Yea rather, blessed are they that hear the word of God, and keep it."},
            {"reference": "John 14:23", "text": "Jesus answered and said unto him, If a man love me, he will keep my words: and my Father will love him, and we will come unto him, and make our abode with him."},
            {"reference": "Deuteronomy 5:33", "text": "Ye shall walk in all the ways which the LORD your God hath commanded you, that ye may live, and that it may be well with you, and that ye may prolong your days in the land which ye shall possess."},
            {"reference": "1 John 5:3", "text": "For this is the love of God, that we keep his commandments: and his commandments are not grievous."},
            {"reference": "Acts 5:29", "text": "Then Peter and the other apostles answered and said, We ought to obey God rather than men."},
            {"reference": "Joshua 24:24", "text": "And the people said unto Joshua, The LORD our God will we serve, and his voice will we obey."},
        ],
    },
    {
        "slug": "evangelism", "title": "Sharing the Gospel", "icon": "fa-bullhorn",
        "description": "The Great Commission is for every believer. Get boldness and fuel for your witness from these verses.",
        "verses": [
            {"reference": "Matthew 28:19", "text": "Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost:"},
            {"reference": "Mark 16:15", "text": "And he said unto them, Go ye into all the world, and preach the gospel to every creature."},
            {"reference": "Romans 1:16", "text": "For I am not ashamed of the gospel of Christ: for it is the power of God unto salvation to every one that believeth; to the Jew first, and also to the Greek."},
            {"reference": "Acts 1:8", "text": "But ye shall receive power, after that the Holy Ghost is come upon you: and ye shall be witnesses unto me both in Jerusalem, and in all Judaea, and in Samaria, and unto the uttermost part of the earth."},
            {"reference": "1 Peter 3:15", "text": "But sanctify the Lord God in your hearts: and be ready always to give an answer to every man that asketh you a reason of the hope that is in you with meekness and fear:"},
            {"reference": "Romans 10:14", "text": "How then shall they call on him in whom they have not believed? and how shall they believe in him of whom they have not heard? and how shall they hear without a preacher?"},
            {"reference": "Matthew 5:16", "text": "Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven."},
            {"reference": "Psalm 96:3", "text": "Declare his glory among the heathen, his wonders among all people."},
            {"reference": "2 Timothy 4:2", "text": "Preach the word; be instant in season, out of season; reprove, rebuke, exhort with all longsuffering and doctrine."},
        ],
    },
    {
        "slug": "friendship", "title": "Friendship & Community", "icon": "fa-user-group",
        "description": "God designed us for relationships. These verses celebrate the gift of godly friends and the beauty of the family of faith.",
        "verses": [
            {"reference": "Proverbs 17:17", "text": "A friend loveth at all times, and a brother is born for adversity."},
            {"reference": "Proverbs 27:17", "text": "Iron sharpeneth iron; so a man sharpeneth the countenance of his friend."},
            {"reference": "Ecclesiastes 4:9-10", "text": "Two are better than one; because they have a good reward for their labour. For if they fall, the one will lift up his fellow: but woe to him that is alone when he falleth; for he hath not another to help him up."},
            {"reference": "John 15:13", "text": "Greater love hath no man than this, that a man lay down his life for his friends."},
            {"reference": "Proverbs 18:24", "text": "A man that hath friends must shew himself friendly: and there is a friend that sticketh closer than a brother."},
            {"reference": "Proverbs 27:9", "text": "Ointment and perfume rejoice the heart: so doth the sweetness of a man's friend by hearty counsel."},
            {"reference": "Hebrews 10:24-25", "text": "And let us consider one another to provoke unto love and to good works: Not forsaking the assembling of ourselves together, as the manner of some is; but exhorting one another: and so much the more, as ye see the day approaching."},
            {"reference": "Romans 12:10", "text": "Be kindly affectioned one to another with brotherly love; in honour preferring one another;"},
            {"reference": "1 Samuel 18:1", "text": "And it came to pass, when he had made an end of speaking unto Saul, that the soul of Jonathan was knit with the soul of David, and Jonathan loved him as his own soul."},
        ],
    },
    {
        "slug": "perseverance", "title": "Perseverance", "icon": "fa-person-running",
        "description": "The race is not to the swift but to those who endure. Draw fresh strength for the long run from these verses.",
        "verses": [
            {"reference": "James 1:12", "text": "Blessed is the man that endureth temptation: for when he is tried, he shall receive the crown of life, which the Lord hath promised to them that love him."},
            {"reference": "Hebrews 10:36", "text": "For ye have need of patience, that, after ye have done the will of God, ye might receive the promise."},
            {"reference": "Romans 5:3-4", "text": "And not only so, but we glory in tribulations also: knowing that tribulation worketh patience; And patience, experience; and experience, hope:"},
            {"reference": "2 Timothy 4:7", "text": "I have fought a good fight, I have finished my course, I have kept the faith:"},
            {"reference": "Hebrews 12:1-2", "text": "Wherefore seeing we also are compassed about with so great a cloud of witnesses, let us lay aside every weight, and the sin which doth so easily beset us, and let us run with patience the race that is set before us, Looking unto Jesus the author and finisher of our faith; who for the joy that was set before him endured the cross, despising the shame, and is set down at the right hand of the throne of God."},
            {"reference": "Revelation 2:10", "text": "Fear none of those things which thou shalt suffer: behold, the devil shall cast some of you into prison, that ye may be tried; and ye shall have tribulation ten days: be thou faithful unto death, and I will give thee a crown of life."},
            {"reference": "1 Corinthians 9:24", "text": "Know ye not that they which run in a race run all, but one receiveth the prize? So run, that ye may obtain."},
            {"reference": "Philippians 3:14", "text": "I press toward the mark for the prize of the high calling of God in Christ Jesus."},
        ],
    },
]

TOPICS_BY_SLUG = {t["slug"]: t for t in TOPIC_VERSES}
